### ISSUE TITLE
cannot find -lv8

### ISSUE THREAD

**Issue by Palsson123** [simenkid/mt7688-cross#1]
I'm using a clean installation of Ubuntu 14.04 64 bit and i have tried this project multiple times both on VMware and on VirtualBox but i always get stuck at the same place. While i run create_env.sh i get this error: `/home/username/mt7688-cross/mt7688sdk/staging_dir/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/bin/../lib/gcc/mipsel-openwrt-linux-uclibc/4.8.3/../../../../mipsel-openwrt-linux-uclibc/bin/ld: cannot find -lv8
collect2: error: ld returned 1 exit status
`
This happens right after:
`-L/home/username/mt7688-cross/v8/out/mipsel.release/lib.target/ -lv8 -ldl`
I can't seem to get past this.
I also tried using this docker with all of this already set up. But I can't seem to be able to build my own local modules. It's complaining about "invalid package.json".

**Comment by simenkid** [comment]
Hi Palsson,

  I'm not sure what happens. May you see if  this [thread](https://github.com/CauldronDevelopmentLLC/CAMotics/issues/97) can do any help?

**Comment by simenkid** [comment]
Hello Palsson,
  Recently, I found that your problem may be caused by the gyp dependency broken (It's google's svn to git migration issue), I just fixed this problem. You may like to try it again. :-)
