### ISSUE TITLE
show wget requirement in readme

### ISSUE THREAD

**Issue by jarrodbell** [simenkid/mt7688-cross#3]
Might be worth adding `wget` to the list of packages that need to be installed to save a little troubleshooting when the `create_env.sh` script continues to run even though the `wget` calls have failed at the beginning.

`wget` is not installed by default on the Ubuntu docker container I was attempting to cross-compile from.

**Comment by simenkid** [comment]
Hello Jarrod, I've added the notice to README, thanks for your feedback.
